# Generated by Django 5.0.7 on 2024-07-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
                ('livraison', models.BooleanField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('prixDebut', models.FloatField()),
                ('prixFin', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
                ('prix', models.FloatField()),
                ('date', models.DateField()),
                ('enchere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='Core.enchere')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixAchat', models.FloatField()),
                ('dateAchat', models.DateField()),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuscom', to='Core.commande')),
                ('enchere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recusdec', to='Core.enchere')),
            ],
        ),
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128, unique=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('EN_VENTE', 'En vente'), ('EN_ENCHERE', 'En enchere'), ('VENDU', 'Vendu'), ('RESERVE', 'Réservé')], default='RESERVE', max_length=12)),
                ('categories', models.ManyToManyField(to='Core.categorie')),
                ('couleurs', models.ManyToManyField(to='Core.couleur')),
                ('qualites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.qualite')),
            ],
        ),
        migrations.AddField(
            model_name='enchere',
            name='tableau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeres', to='Core.tableau'),
        ),
        migrations.AddField(
            model_name='commande',
            name='tableau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='Core.tableau'),
        ),
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.FloatField(blank=True, null=True)),
                ('largeur', models.SmallIntegerField()),
                ('hauteur', models.SmallIntegerField()),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='Core.tableau')),
            ],
        ),
    ]
