# Generated by Django 5.0.7 on 2024-07-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='adresse',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='livraison',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
