# Generated by Django 5.0.7 on 2024-07-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_declaration_adresse_declaration_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('pourcentage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='image',
            field=models.ImageField(null=True, upload_to='textures/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='tableau_images/')),
                ('description', models.TextField(blank=True)),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Core.tableau')),
            ],
        ),
    ]
